temperaturetest: temperature.o lab_10_unit_test.o
	g++ -Wall -g -o temperature temperature.o lab_10_unit_test.o

lab10: temperature.cpp
	g++ -Wall -g -c temperature.cpp
	
lab10unittest: lab_10_unit_test.cpp
	g++ -Wall -g -c lab_10_unit_test.cpp