itemtest: magic_item.o food_item.o item.o lab_10_unit_test.o
	g++ -Wall -g -o item item.o food_item.o magic_item.o lab_10_unit_test.o

item: item.cpp
	g++ -Wall -g -c item.cpp
	
food_item: food_item.cpp
	g++ -Wall -g -c food_item.cpp

magic_item: magic_item.cpp
	g++ -Wall -g -c magic_item.cpp
	
lab_10_unit_test:lab_10_unit_test.cpp
	g++ -Wall -g -c lab_10_unit_test.cpp