moneytest: money.o lab_11_unit_test.o
	g++ -Wall -g -o money money.o lab_11_unit_test.o

lab11: money.cpp
	g++ -Wall -g -c money.cpp
	
lab11unittest: lab_11_unit_test.cpp
	g++ -Wall -g -c lab_11_unit_test.cpp