lab23test: bst_node.o lab_23_unit_test.o
	g++ -Wall -g -o bstnode bst_node.o lab_23_unit_test.o

bst_node: bst_node.cpp
	g++ -Wall -g -c bst_node.cpp
	
lab23unittest: lab_23_unit_test.cpp
	g++ -Wall -g -c lab_23_unit_test.cpp