lab12test: lab_12.o lab_12_unit_test.o
	g++ -Wall -g -o lab12 lab_12.o lab_12_unit_test.o

lab12: lab_12.cpp
	g++ -Wall -g -c lab_12.cpp
	
lab12unittest: lab_12_unit_test.cpp
	g++ -Wall -g -c lab_12_unit_test.cpp