sllisttest: sl_node.o lab_18_unit_test.o sl_list.o
	g++ -Wall -g -o sllist sl_node.o sl_list.o lab_18_unit_test.o 

slnode: sl_node.cpp
	g++ -Wall -g -c sl_node.cpp
	
sl_list: sl_list.cpp
	g++ -Wall -g -c sl_list.cpp
	
lab18unittest: lab_18_unit_test.cpp
	g++ -Wall -g -c lab_18_unit_test.cpp