lab23test: bst_node.o lab_24_unit_test.o bs_tree.o
	g++ -Wall -g -o bstree bst_node.o bs_tree.o lab_24_unit_test.o

bs_tree: bs_tree.cpp
	g++ -Wall -g -c bs_tree.cpp
	
bst_node: bst_node.cpp
	g++ -Wall -g -c bst_node.cpp
	
lab23unittest: lab_24_unit_test.cpp
	g++ -Wall -g -c lab_24_unit_test.cpp